// AUTO-GENERATED by scripts/generate-index-html.js — DO NOT EDIT.
// Source: dist/index.html after `expo export --platform web`.
// Run via the Vercel buildCommand; committed so Jest doesn't need to
// regenerate. Update by running the script locally or triggering a
// fresh Vercel build.

export const INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Scarlet>Fire - Grateful Dead Archive</title>
    <!-- The \`react-native-web\` recommended style reset: https://necolas.github.io/react-native-web/docs/setup/#root-element -->
    <style id="expo-reset">
      /* These styles make the body full-height */
      html,
      body {
        height: 100%;
      }
      /* These styles disable body scrolling if you are using <ScrollView> */
      body {
        overflow: hidden;
      }
      /* These styles make the root element full-height */
      #root {
        display: flex;
        height: 100%;
        flex: 1;
      }
    </style>
  <meta name="theme-color" content="#121212">
<meta name="description" content="Browse and stream 40+ years of Grateful Dead live shows">
<link rel="icon" href="/favicon.ico" /></head>

  <body>
    <!-- Use static rendering with Expo Router to support running without JavaScript. -->
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <!-- The root element for your Expo app. -->
    <div id="root"></div>
  <script src="/_expo/static/js/web/index-e63f38cf6d84a4e494f3ed4536752f3f.js" defer></script>
</body>
</html>
`;
