// Auto-generated by scripts/generateVideoSources.js
// Run "node scripts/generateVideoSources.js" after adding new videos

export const VIDEO_SOURCES = [
  require('../../assets/videos/background1.mov'),
  require('../../assets/videos/background2.mov'),
  require('../../assets/videos/background3.mov'),
  require('../../assets/videos/background4.mov'),
  require('../../assets/videos/background5.mov'),
  require('../../assets/videos/background6.mov'),
  require('../../assets/videos/background7.mov'),
  require('../../assets/videos/background8.mov'),
];

export const VIDEO_COUNT = 8;
