const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Expo config plugin: mark Google's Obj-C pods as modular so the Swift pod
 * AppCheckCore (pulled in transitively by @react-native-google-signin) can
 * import them when CocoaPods builds static libraries.
 *
 * Without this, a fresh `pod install` (which EAS runs on every build — the
 * Podfile is regenerated by prebuild and Podfile.lock is not committed)
 * fails with:
 *   "The Swift pod `AppCheckCore` depends upon `GoogleUtilities` and
 *    `RecaptchaInterop`, which do not define modules."
 * Broke starting with RecaptchaInterop 101 / AppCheckCore 11.x (July 2026);
 * EAS builds 82-84 failed at the Install pods phase.
 */
const MARKER = 'use_expo_modules!';
const INJECTION = `${MARKER}

  # Added by plugins/withModularHeaders.js — see that file for why.
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true`;

function withModularHeaders(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfilePath, 'utf8');

      if (!contents.includes(MARKER)) {
        throw new Error(
          `withModularHeaders: expected to find "${MARKER}" in ${podfilePath} — the Podfile template changed; update this plugin.`
        );
      }
      if (!contents.includes(':modular_headers')) {
        contents = contents.replace(MARKER, INJECTION);
        fs.writeFileSync(podfilePath, contents);
      }
      return config;
    },
  ]);
}

module.exports = withModularHeaders;
