#!/usr/bin/env node

/**
 * This script scans the assets/videos folder and generates a TypeScript file
 * with all video sources. Run this after adding new videos:
 *
 *   node scripts/generateVideoSources.js
 */

const fs = require('fs');
const path = require('path');

const VIDEOS_DIR = path.join(__dirname, '../assets/videos');
const OUTPUT_FILE = path.join(__dirname, '../src/constants/videoSources.generated.ts');

// Supported video extensions
const VIDEO_EXTENSIONS = ['.mov', '.mp4', '.m4v', '.webm'];

// Get all video files
const videoFiles = fs.readdirSync(VIDEOS_DIR)
  .filter(file => {
    const ext = path.extname(file).toLowerCase();
    return VIDEO_EXTENSIONS.includes(ext) && !file.startsWith('.');
  })
  .sort();

if (videoFiles.length === 0) {
  console.error('No video files found in assets/videos/');
  process.exit(1);
}

// Generate the TypeScript file
const requires = videoFiles
  .map(file => `  require('../../assets/videos/${file}'),`)
  .join('\n');

const content = `// Auto-generated by scripts/generateVideoSources.js
// Run "node scripts/generateVideoSources.js" after adding new videos

export const VIDEO_SOURCES = [
${requires}
];

export const VIDEO_COUNT = ${videoFiles.length};
`;

fs.writeFileSync(OUTPUT_FILE, content);

console.log(`Generated ${OUTPUT_FILE}`);
console.log(`Found ${videoFiles.length} videos: ${videoFiles.join(', ')}`);
